Listen 0.0.0.0:631
ServerAlias *
WebInterface Yes
LogLevel warn
MaxLogSize 0

# Política de autenticación
DefaultAuthType Basic
DefaultEncryption Never

# Acceso web básico
<Location />
  Order allow,deny
  Allow from 192.168.1.0/24
  Allow from 10.42.0.0/16
</Location>

# Acceso administrativo
<Location /admin>
  Order allow,deny
  Allow from 192.168.1.0/24
  Allow from 10.42.0.0/16
</Location>

<Location /admin/conf>
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow from 192.168.1.0/24
  Allow from 10.42.0.0/16
</Location>

# Permitir compartir impresoras
Browsing On
BrowseLocalProtocols dnssd
DefaultShared Yes
