apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pihole-headers
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/component: middleware
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pihole-ratelimit
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/component: middleware
spec:
  rateLimit:
    average: 100
    burst: 200
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pihole-redirect-http
  namespace: pihole
spec:
  redirectScheme:
    scheme: https
    permanent: true
